# Spring Boot Port Configuration
server.port=8085

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/easemyhome_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=D2_89806_Shubham
spring.datasource.password=Shubhu@2210
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Enable API logs
logging.level.org.springframework.web=INFO
logging.level.com.easemyhome=DEBUG

# Spring Mail Configurations (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ssakande4@gmail.com
spring.mail.password=bzegpxbcznscfnpg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Increase payload and file upload limits for base64 image strings
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=50MB

# Cloudinary Integration Credentials (for future backend use)
cloudinary.cloud-name=ka46s4mh
cloudinary.api-key=713249123583763
cloudinary.api-secret=eF4rTySKqrmQnxS3DSlaHf-JSZA
cloudinary.url=cloudinary://713249123583763:eF4rTySKqrmQnxS3DSlaHf-JSZA@ka46s4mh

# Google OAuth 2.0 Client ID
google.client-id=136156023067-sn4hhloi6hcn5b6th813tqctpcorbpkv.apps.googleusercontent.com
